name: 'Sesame GH Action'
description: 'Greet someone and record the time'
inputs:
  command:
    description: 'Which command of Sesame binary to run.'
    required: true
    default: 'trackomate'
  arg1:
    description: 'Arg1 for the command.'
    required: true
    default: '-t'
  arg1Value:
    description: 'Arg1 Value for the command.'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '/sesame'
    - ${{ inputs.command }}
    - ${{ inputs.arg1 }}
    - ${{ inputs.arg1Value }}