name: 'Sesame GH Action'
description: 'Greet someone and record the time'
inputs:
  command:
    description: 'Which command of Sesame binary to run.'
    required: true
    default: 'trackomate'
  flag1:
    description: '1st flag for the command.'
    required: true
    default: '-i'
  flag1Arg:
    description: 'Argument for the 1st flag of the command.'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '/sesame'
    - ${{ inputs.command }}
    - ${{ inputs.flag1 }}
    - ${{ inputs.flag1Arg }}